steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dropviz-$BRANCH_NAME', '--build-arg', 'BRANCH=$BRANCH_NAME', '.']
images: ['gcr.io/$PROJECT_ID/dropviz-$BRANCH_NAME']

